apps:
  - name: bancho-service-rs-api
    environment: production
    codebase: bancho-service-rs
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
    container:
      image:
        repository: osuakatsuki/bancho-service-rs
        tag: latest
      port: 80
      readinessProbe:
        httpGet:
          path: /_health
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 3
        successThreshold: 1
        failureThreshold: 3
      resources:
        limits:
          cpu: 1000m
          memory: 350Mi
        requests:
          cpu: 200m
          memory: 250Mi
      env:
        - name: APP_COMPONENT
          value: api
      imagePullSecrets:
        - name: osuakatsuki-registry-secret
    service:
      type: ClusterIP
      port: 80

  - name: bancho-service-rs-pubsub-daemon
    environment: production
    codebase: bancho-service-rs
    replicaCount: 1
    container:
      image:
          repository: osuakatsuki/bancho-service-rs
          tag: latest
      port: 80
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 75m
          memory: 75Mi
      env:
        - name: APP_COMPONENT
          value: pubsub-daemon
      imagePullSecrets:
        - name: osuakatsuki-registry-secret