#[derive(sqlx::FromRow)]
pub struct Stats {
    pub user_id: i64,
    pub mode: i16,
    pub ranked_score: u64,
    pub total_score: u64,
    pub playcount: u32,
    pub replays_watched: u32,
    pub total_hits: u32,
    pub level: u32,
    pub avg_accuracy: f64,
    pub pp: u32,
    pub playtime: u64,
    pub xh_count: u64,
    pub x_count: u64,
    pub sh_count: u64,
    pub s_count: u64,
    pub a_count: u64,
    pub b_count: u64,
    pub c_count: u64,
    pub d_count: u64,
    pub max_combo: u32,
    pub latest_pp_awarded: u64,
}
